ci: deploy apps only after releae

diff --git a/.github/workflows/deploy-storybook.yml b/.github/workflows/deploy-storybook.yml
--- a/.github/workflows/deploy-storybook.yml
+++ b/.github/workflows/deploy-storybook.yml
@@ -3,9 +3,10 @@ env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_MATERIAL_STORYBOOK_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MATERIAL_STORYBOOK_PROJECT_ID }}
 on:
-  push:
-    branches:
-      - main
+  workflow_run:
+    workflows: ["Release"]
+    types:
+      - completed
 
 concurrency: ${{ github.workflow }}-${{ github.ref }}
 
@@ -17,6 +18,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check if release was successful
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "Previous release workflow did not succeed, aborting."
+            exit 1
+          fi
+
       - name: Checkout main
         uses: actions/checkout@v3
         with:
