ci: implement pipeline for release

diff --git a/.github/workflows/deploy-demo.yml b/.github/workflows/deploy-demo.yml
--- a/.github/workflows/deploy-demo.yml
+++ b/.github/workflows/deploy-demo.yml
@@ -1,11 +1,14 @@
-name: Deployment of Demo for material.resrc.ch
+name: Deploy Demo
 env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_MATERIAL_DEMO_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MATERIAL_DEMO_PROJECT_ID }}
 on:
-  push:
-    branches:
-      - main
+  workflow_run:
+    workflows: ["Version or Publish"]
+    types:
+      - completed
+
+concurrency: ${{ github.workflow }}-${{ github.ref }}
 
 jobs:
   deploy-demo:
@@ -15,6 +18,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check if release was successful
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
+            echo "Previous release workflow did not succeed, aborting."
+            exit 1
+          fi
+
       - name: Checkout main
         uses: actions/checkout@v3
         with:
@@ -48,7 +58,7 @@ jobs:
             ${{ runner.os }}-pnpm-store-
 
       - name: Install dependencies
-        run: pnpm install
+        run: pnpm install --frozen-lockfile
 
       - name: Run build
         run: pnpm build
